_version: 1.2.0
dev/assets/css/global.css: 53fdc11d00fbbcc2516c23ef72d8b915
dev/assets/js/global.js: f17a2f32b6837244881a04ee5aa94015
dev/assets/js/home.js: c2d1daf919a68fcead2b7b2f30b1dbf2
dev/features/bmi/script.js: 30677da7e3a25c3028c8d9e561017e22
dev/features/bookmark-creator/style.css: 516e96d6691fd55acf6219fe25c410d0
dev/features/bookmark-creator/script.js: 6674c24de2409b377d993ad95e3c50fe
dev/features/business-tax/style.css: c90ca5b29db517fe3544819a99dba89b
dev/features/business-tax/script.js: 3d17a707b684df7be5fc8401c4f7f2af
dev/features/compound-interest/style.css: c687ee795f3d596fed6fb4a2dcf96f48
dev/features/compound-interest/script.js: 631b977ebf4975d2e60ca218c9e9d27a
dev/features/freelancer-tax/style.css: 27fb3759f4b4d5d0a21a68509d60f818
dev/features/freelancer-tax/script.js: 9dda31f62ae6f33223a7c452d1cabd85
dev/features/hash-toolkit/style.css: 5a8ec0323a5d1eba85bf6e40f06d4eb0
dev/features/hash-toolkit/script.js: 7b53d557089be8fae184a58bc317d8af
dev/features/inflation-calculator/style.css: 97364f43e45e7953209bf7bc6ccbb5cd
dev/features/inflation-calculator/script.js: 61ccfd80bef82a594e295962a13d357c
dev/features/investment-calc/style.css: f21282ad07ac8a53fadafb1bccfdef05
dev/features/investment-calc/script.js: 057c661342afa6435ca8f2009dec2008
dev/features/json-toolkit/style.css: 0c8cf50a053bc52d892a339099bedb2e
dev/features/json-toolkit/script.js: bce6079726a05540a76ddbff3faec135
dev/features/jwt-toolkit/style.css: 71e867a477c9c510926ad64c1eb894b8
dev/features/jwt-toolkit/script.js: 9c6a2a51a96110e4fcf96b79e31e725f
dev/features/loan-calculator/style.css: a03d1f59c592b8a58cf296f89ac00ea5
dev/features/loan-calculator/script.js: 9ae53b791c7ba89bcdb412cba591ce96
dev/features/lorem-ipsum/style.css: 7355d14f66673f115419009a17ff2e7b
dev/features/lorem-ipsum/script.js: a023071d56030386fc6af199e1147e84
dev/features/lunar-calendar/style.css: 8c8afc0bd03e291566adf6680f195ce2
dev/features/lunar-calendar/script.js: 9646122d94d91e842880c2fefc5ac39a
dev/features/ot-calculator/style.css: 97b5d4b101f114549196829dab5cb52f
dev/features/ot-calculator/script.js: 1fc72a1f4a77dea2c0cb2ee2de1f73e2
dev/features/password-generator/style.css: 9840539e4340e268851c2fb4a68a3042
dev/features/password-generator/script.js: 80035ba6531c89246f862affd5edecf6
dev/features/percentage-calculator/style.css: a32b33318eb90fc7674e32ba5daf3711
dev/features/percentage-calculator/script.js: 230e4924a3efe9667ba70e6dbf7a7455
dev/features/qr-generator/style.css: 3f83e2d3206c368755a48fa2b5fce1d3
dev/features/qr-generator/script.js: 6081763578ea38145ea447fbe848ca6f
dev/features/random-toolkit/style.css: 53513ee0f796689d538c41f5a0ecedb5
dev/features/random-toolkit/script.js: 524b8b3580ed4c362b7305dae4bcf311
dev/features/savings-interest/style.css: b5545ede643c9f3843a415fd9c6dd413
dev/features/savings-interest/script.js: 96597e000a43a8c09cbc3c3433c56a17
dev/features/social-insurance/style.css: 617831f4f1dc0cf8b00ef81264960f0e
dev/features/social-insurance/script.js: c02d9b4541cb156b17a5bae9a0bf4103
dev/features/tax/style.css: ea440860808922d53eb4c289c69a6dee
dev/features/tax/script.js: 5277db5d70abd577db7468440775abfb
dev/features/text-diff/style.css: b1d84dd78fb3a7b53f8259fba7e5383b
dev/features/text-diff/script.js: 1ed057fca33b3f5f5756aac9365b735f
dev/features/text-formatter/style.css: df5e107dc7d228735591b55e7f01e601
dev/features/text-formatter/script.js: 49fb054ec0a41f0c417401427b4ced84
dev/features/timestamp-converter/style.css: c5ba30027ddf855a3a46d8b319af8ca4
dev/features/timestamp-converter/script.js: 35e975fe69bb71346706572263c1bc91
dev/features/unit-converter/style.css: 0dfe62c2913f4f099bc11ddfe1f7a7bb
dev/features/unit-converter/script.js: 0e7b2bcf02e1fd648371b4db4e18213e
dev/features/url-toolkit/style.css: e62dbbe317f5dde8eaa40a99107a1630
dev/features/url-toolkit/script.js: 0ea96baca49a52653e2af6945f22c017
dev/features/uuid-generator/style.css: f08ff4cf4e34a15bc202e686af5929a7
dev/features/uuid-generator/script.js: 02c3a554d589676772c1763e0372e71b
dev/features/word-counter/style.css: 0c4dc4c0471e938630ff068c1946e607
dev/features/word-counter/script.js: 6dc3e6d82d8b1a8a2ca172a3adcff814
dev/page/pages/404.ejs: e33bdf8c602155a5beafa541520a3911
dev/page/pages/about.ejs: 2b2bd920be89037472579441df0cae39
dev/page/pages/categories.ejs: 77912f90e69e79c75a44440bd242f15a
dev/page/pages/privacy.ejs: d069265889294d449c927fd85c03ee6f
dev/page/pages/terms.ejs: 0e1cab6c1c9ecf5bf76e0d4dee6e6bcf
dev/page/features/bmi/index.ejs: d3008a32a95d1dd20d00cd3a212cd995
dev/page/features/bookmark-creator/index.ejs: fc640e91c03222df06352ebe306e7838
dev/page/features/business-tax/index.ejs: 8cd93d266dc82ca2520055b123e8f77f
dev/page/features/compound-interest/index.ejs: 72cde45c26856a51c34801a7e8cbe9b0
dev/page/features/freelancer-tax/index.ejs: 67ef1069f903cbe12ac2ffe1d7a46183
dev/page/features/hash-toolkit/index.ejs: 2e6f4e574b71b990136fb379a80aef57
dev/page/features/inflation-calculator/index.ejs: b028d7e5e544a14c346839a8abd191b3
dev/page/features/investment-calc/index.ejs: 5ff5ea7dc9121018f7e2481902e6fb8c
dev/page/features/json-toolkit/index.ejs: 2fd9cd1c143a34582803fe00c293b962
dev/page/features/jwt-toolkit/index.ejs: 4039c6f7ca5b0915370e30954c5cc56d
dev/page/features/loan-calculator/index.ejs: 9cbad0c3a704b13fb1316a357e8c102d
dev/page/features/lorem-ipsum/index.ejs: 03699cba28cc88e3b7a95cdc66785696
dev/page/features/lunar-calendar/index.ejs: 4aa7b947f32de40bec7f43a06bdc97c8
dev/page/features/ot-calculator/index.ejs: d464f598dc264eef3d2b7dd11b70e342
dev/page/features/password-generator/index.ejs: b728f3ea94842e37b3e0dd44d3b607d8
dev/page/features/percentage-calculator/index.ejs: 3529d76818767b4c2d421aa8ac9dd4c2
dev/page/features/qr-generator/index.ejs: 5c7873161651c4959c03f3e64033fc0f
dev/page/features/random-toolkit/index.ejs: d97c2f1f91c5135c0609062c6964cafb
dev/page/features/savings-interest/index.ejs: aea7ed5ed536230b6bebd3e438ae87ea
dev/page/features/social-insurance/index.ejs: 232e6630ce179745bc4a73439f2d528e
dev/page/features/tax/index.ejs: d94dcc48b345632d589f43338416f1b7
dev/page/features/text-diff/index.ejs: 2932fc5644771e95e4d817ec38e7d429
dev/page/features/text-formatter/index.ejs: de4f987909bd7952d3d49f4dd20d034c
dev/page/features/timestamp-converter/index.ejs: 556ca6a755842ebc8c990af6ad7e494b
dev/page/features/unit-converter/index.ejs: b5410864c64a4e0eec959c50314263dd
dev/page/features/url-toolkit/index.ejs: b647556379972fa019dbbe32e12eab68
dev/page/features/uuid-generator/index.ejs: bd3d97c8c46845dbfc8fed7fc27a3c24
dev/page/features/word-counter/index.ejs: 34951eda4603247520a11be61c84e5f3
dev/data/data/global.yaml: e0664b57cdffaa8533d031340f387e60
dev/locales/en/locales/en/common.yaml: 259877a0e8ddbe9c629420eb8c75c729
dev/locales/vi/locales/vi/common.yaml: 63309dcd09929fe1f414b9ae7598c065
dev/include/includes/footer.ejs: 7587c51c8695f7f5058f27ab6e7bfb3d
dev/include/includes/head.ejs: 8fa69c6eb9f082d42ad9b69550420b99
dev/include/includes/header.ejs: 0cb89fa0fcd0f664b97cfee067787a57
dev/include/includes/layout.ejs: baf086a99888469507b34f12376a46a1
dev/include/includes/schema.ejs: 2cb8ee0f32443abb85637f9a860c31ae
dev/config/bmi/features/bmi/tool.yaml: 386aff872770941a6757f49a748912dc
dev/feat-locales/bmi/features/bmi/locales/en.yaml: 6b1654da387a662a57e562f0dd0a1fae
dev/feat-locales/bmi/features/bmi/locales/vi.yaml: 4939d29a90bb82f6b1b81b64cd199f93
dev/config/bookmark-creator/features/bookmark-creator/tool.yaml: d687e33dc116dfeec3abe33f9ac3ad3e
dev/feat-locales/bookmark-creator/features/bookmark-creator/locales/en.yaml: eee39dc4abd51d20db1efcd23ae79437
dev/feat-locales/bookmark-creator/features/bookmark-creator/locales/vi.yaml: 4bcb2b20ac3396fbd95980ce5d032d9b
dev/config/business-tax/features/business-tax/tool.yaml: 7a33095ce4436f707866f032b8079756
dev/feat-locales/business-tax/features/business-tax/locales/en.yaml: 6c28974240dd462acb252dd3100584e4
dev/feat-locales/business-tax/features/business-tax/locales/vi.yaml: 9938048b934e9a3925230a95a7a28c7e
dev/config/compound-interest/features/compound-interest/tool.yaml: 54b193adc29766f51d4a3d1d0a24f722
dev/feat-locales/compound-interest/features/compound-interest/locales/en.yaml: 1c98ad9d0c59f3ce81dcf796383cd270
dev/feat-locales/compound-interest/features/compound-interest/locales/vi.yaml: bf4dcf6a2b203757c0272af6235c3355
dev/config/freelancer-tax/features/freelancer-tax/tool.yaml: 74789859b79e545fe5f83b13f3dc4aca
dev/feat-locales/freelancer-tax/features/freelancer-tax/locales/en.yaml: 1eff4ea203cca3b0e58102f3521480e1
dev/feat-locales/freelancer-tax/features/freelancer-tax/locales/vi.yaml: 1048e01d8e8bf87d9a88e2f668d15942
dev/config/hash-toolkit/features/hash-toolkit/tool.yaml: af5f8b1087c3ef1657a78e319185a419
dev/feat-locales/hash-toolkit/features/hash-toolkit/locales/en.yaml: c4d64919629f75b93ff8248d9f8f06f0
dev/feat-locales/hash-toolkit/features/hash-toolkit/locales/vi.yaml: f57c2c4dfbf38159de981a3394612cbb
dev/config/inflation-calculator/features/inflation-calculator/tool.yaml: 007d599ef4a695e69a5b404d6ed2cd6f
dev/feat-locales/inflation-calculator/features/inflation-calculator/locales/en.yaml: 3a70a794649a9c7e1d52e855bf5c6d1a
dev/feat-locales/inflation-calculator/features/inflation-calculator/locales/vi.yaml: ac75c15af66d4720655a54ec314f7b2e
dev/config/investment-calc/features/investment-calc/tool.yaml: a1f0383380f635f077e68cf90118e554
dev/feat-locales/investment-calc/features/investment-calc/locales/en.yaml: 9e26b5bbbb7bbf2e8b2a6146d6497998
dev/feat-locales/investment-calc/features/investment-calc/locales/vi.yaml: 99ad7d4e074053ef05f74945dfb6e670
dev/config/json-toolkit/features/json-toolkit/tool.yaml: f4518ab5fa97a03cff0e1e8d84acd09b
dev/feat-locales/json-toolkit/features/json-toolkit/locales/en.yaml: 2a05dffde55672e3283f335d2cee7231
dev/feat-locales/json-toolkit/features/json-toolkit/locales/vi.yaml: fc6993fba0bde44ffc97535007390af8
dev/config/jwt-toolkit/features/jwt-toolkit/tool.yaml: 188171b59391bf8d1358d5577c5b2a5c
dev/feat-locales/jwt-toolkit/features/jwt-toolkit/locales/en.yaml: cbcd61687a23be7b2455c86dc70dfc0d
dev/feat-locales/jwt-toolkit/features/jwt-toolkit/locales/vi.yaml: 16d18e0d4d4544a7707dd3180c82d71d
dev/config/loan-calculator/features/loan-calculator/tool.yaml: 474a7131db51b974fcd54b89205415fd
dev/feat-locales/loan-calculator/features/loan-calculator/locales/en.yaml: be107aa1e85b372ae2b5a42656722483
dev/feat-locales/loan-calculator/features/loan-calculator/locales/vi.yaml: 8e85c074eeb6ab2a06e976554096a952
dev/config/lorem-ipsum/features/lorem-ipsum/tool.yaml: 8727ada6091b62d1c82439de48bc85a3
dev/feat-locales/lorem-ipsum/features/lorem-ipsum/locales/en.yaml: be9c6d2877238353c973efd3f821c637
dev/feat-locales/lorem-ipsum/features/lorem-ipsum/locales/vi.yaml: df0dab2c1cab43311fd92935081d4d75
dev/config/lunar-calendar/features/lunar-calendar/tool.yaml: 3835b023734d574fd27a70324779e185
dev/feat-locales/lunar-calendar/features/lunar-calendar/locales/en.yaml: 66a0edbedac54016de4886a46fce4678
dev/feat-locales/lunar-calendar/features/lunar-calendar/locales/vi.yaml: 4622ef5d28dde3ed0ab2e63b3ebf610f
dev/config/ot-calculator/features/ot-calculator/tool.yaml: a303e5d8ee02bf3d92cbd9a9b611854b
dev/feat-locales/ot-calculator/features/ot-calculator/locales/en.yaml: 3015e4b3373120ec7d0cc0968b31ed42
dev/feat-locales/ot-calculator/features/ot-calculator/locales/vi.yaml: 7f8d93e7ad73b03bbf8c3134d7566cbc
dev/config/password-generator/features/password-generator/tool.yaml: e09ac492c18a63f3fec482eb345f9b4f
dev/feat-locales/password-generator/features/password-generator/locales/en.yaml: dbff2cb4219447fb43fb4ab67085d21f
dev/feat-locales/password-generator/features/password-generator/locales/vi.yaml: 26594416610edc5b6cd75fb723cd15ab
dev/config/percentage-calculator/features/percentage-calculator/tool.yaml: 7e691f837e6b59c564b9c08504c94cf9
dev/feat-locales/percentage-calculator/features/percentage-calculator/locales/en.yaml: bb667f80f9211a98b5e170d7d8e3b7d5
dev/feat-locales/percentage-calculator/features/percentage-calculator/locales/vi.yaml: 54d88d3bff84af4084f5d4c72ce80e63
dev/config/qr-generator/features/qr-generator/tool.yaml: 0d6f04237e03dd3916eb5ec03d6a00ae
dev/feat-locales/qr-generator/features/qr-generator/locales/en.yaml: 6489e32b274177e0896947b1d64b3420
dev/feat-locales/qr-generator/features/qr-generator/locales/vi.yaml: 73175068a1ecdf3f3f1815d7d9e2d47f
dev/config/random-toolkit/features/random-toolkit/tool.yaml: 124af6bcfa023d0fe861eba89fc6f5c2
dev/feat-locales/random-toolkit/features/random-toolkit/locales/en.yaml: 5fe179f67763527e9bf375ad302f85af
dev/feat-locales/random-toolkit/features/random-toolkit/locales/vi.yaml: e7d7ace15444a24903ef2909c939690e
dev/config/savings-interest/features/savings-interest/tool.yaml: cc7ee0f5304b226c0200307ef0fb748d
dev/feat-locales/savings-interest/features/savings-interest/locales/en.yaml: c5160cf9517b9a2938d704778ded106c
dev/feat-locales/savings-interest/features/savings-interest/locales/vi.yaml: e7bba39901084967c57eb2005d047c54
dev/config/social-insurance/features/social-insurance/tool.yaml: 22be3fec0672f8c5b86721d77188b9d1
dev/feat-locales/social-insurance/features/social-insurance/locales/en.yaml: 189e29d947f2caf9cf2bda4a6852c3aa
dev/feat-locales/social-insurance/features/social-insurance/locales/vi.yaml: 8f7794fc92a2937dabd25007650273f2
dev/config/tax/features/tax/tool.yaml: fcde7881a3960ff2eaf9983ae25a6236
dev/feat-locales/tax/features/tax/locales/en.yaml: 1292efa5b8cd1996daae96ab1fe34778
dev/feat-locales/tax/features/tax/locales/vi.yaml: 94110fc00d303a40106539ec716c211e
dev/config/text-diff/features/text-diff/tool.yaml: 253cd0b0b1bc2794b5a66804db676c0b
dev/feat-locales/text-diff/features/text-diff/locales/en.yaml: a2cc58401a356a3adb20f022ca99049d
dev/feat-locales/text-diff/features/text-diff/locales/vi.yaml: d889b087f98f0976a771f3ea2c737964
dev/config/text-formatter/features/text-formatter/tool.yaml: 53b34355e1eabbe8f4c44b9e4510beaf
dev/feat-locales/text-formatter/features/text-formatter/locales/en.yaml: cd253789e981dcb6b073e8fb57023cfe
dev/feat-locales/text-formatter/features/text-formatter/locales/vi.yaml: 866465d5d64a387e34b89ece96b15e5a
dev/config/timestamp-converter/features/timestamp-converter/tool.yaml: 0d546b6b4b3e43d011345eb6195c7c64
dev/feat-locales/timestamp-converter/features/timestamp-converter/locales/en.yaml: 227abdd5b2a1730c2e1181f38569e7b9
dev/feat-locales/timestamp-converter/features/timestamp-converter/locales/vi.yaml: 1caa769e772a0ccbabb473d24bcd81b3
dev/config/unit-converter/features/unit-converter/tool.yaml: d5fda0ee9cf65774277f6f36adc0e121
dev/feat-locales/unit-converter/features/unit-converter/locales/en.yaml: 46d2b3fbb9f4feaf29f5acf295111fef
dev/feat-locales/unit-converter/features/unit-converter/locales/vi.yaml: f2c8692e81d4a45bcafdbf5f941dbbbf
dev/config/url-toolkit/features/url-toolkit/tool.yaml: 5576b6a1b54ba0fc26e22129d5a9d0d7
dev/feat-locales/url-toolkit/features/url-toolkit/locales/en.yaml: 4dfd8293711dfa7efb4e61fea97f104d
dev/feat-locales/url-toolkit/features/url-toolkit/locales/vi.yaml: e9cd64ab96f71597aec479af51d7e9ea
dev/config/uuid-generator/features/uuid-generator/tool.yaml: 66bbb558bf8832ff160d05c2314b1a94
dev/feat-locales/uuid-generator/features/uuid-generator/locales/en.yaml: 140660664b5980a324762dee7cd12317
dev/feat-locales/uuid-generator/features/uuid-generator/locales/vi.yaml: 79b0da2a30addfd0dac1889aee633d25
dev/config/word-counter/features/word-counter/tool.yaml: add21237c96e5db1b0f1b528c404fc8e
dev/feat-locales/word-counter/features/word-counter/locales/en.yaml: f62c3d50f103d7c3aa77ebc781e402da
dev/feat-locales/word-counter/features/word-counter/locales/vi.yaml: 423199896557505629eb8a360f185653
